### ISSUE TITLE
Does it support Gnuradio v3.9.0 and python3?

### ISSUE THREAD

**Issue by guokr321** [drmpeg/gr-dvbs2rx#10]
Hello,
This is a wonderful module.
When I use Gnuradio v3.9.0 and python3.6.9, cmake will:
-- Checking for module SWIG
-- Found SWIG version 3.0.12.
-- Found SWIG: /usr/bin/swig3.0  
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.6m.so (found version "3.6.9") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.6m.so (found suitable version "3.6.9", minimum required is "2") 
-- Performing Test HAVE_WNO_UNUSED_BUT_SET_VARIABLE
-- Performing Test HAVE_WNO_UNUSED_BUT_SET_VARIABLE - Success
Traceback (most recent call last):
  File "<string>", line 2, in <module>
TypeError: Unicode-objects must be encoded before hashing
CMake Error at /usr/local/lib/cmake/gnuradio/UseSWIG.cmake:200 (add_executable):
  add_executable called with incorrect number of arguments
Call Stack (most recent call first):
  /usr/local/lib/cmake/gnuradio/UseSWIG.cmake:257 (SWIG_ADD_SOURCE_TO_MODULE)
  /usr/local/lib/cmake/gnuradio/GrSwig.cmake:189 (SWIG_ADD_MODULE)
  swig/CMakeLists.txt:51 (GR_SWIG_MAKE)

You have called ADD_LIBRARY for library _dvbs2rx_swig without any source files. This typically indicates a problem with your CMakeLists.txt file
CMake Error at /usr/local/lib/cmake/gnuradio/GrSwig.cmake:227 (GR_LIBTOOL):
  Unknown CMake command "GR_LIBTOOL".
Call Stack (most recent call first):
  swig/CMakeLists.txt:56 (GR_SWIG_INSTALL)

Thanks.

**Comment by drmpeg** [comment]
Sorry, no support for GNU Radio 3.9. It's too soon to bother with 3.9 since the API could change again (it's already changed twice from GNU Radio 3.8).

**Comment by guokr321** [comment]
OK, thanks

**Comment by drmpeg** [comment]
I went ahead and ported to GNU Radio 3.9 on the master branch.
