### ISSUE TITLE
LDPC decode performances

### ISSUE THREAD

**Issue by adibacco** [drmpeg/gr-dvbs2rx#12]
Can you share performance data of LDPC decode on your platform?

**Comment by drmpeg** [comment]
Define "performance".

**Comment by adibacco** [comment]
Thank you for your attention and sorry for the ill posed question. Most of the times I find  a figure in Mbps to assess how fast the LDPC decoder is,  with a given hardware and number of iterations. 

SD-FEC from Xilinx reports:
3.03 Gb/s for LDPC Decode @ 8 iterations
20.34 Gb/s for LDPC Encode

I imagine that a CPU or GPU based LDPC decoder is much slower.

**Comment by drmpeg** [comment]
It's pretty slow. On an Intel Xeon E5-1650 v4 CPU and 8 iterations, it's about 5 to 20 Mbps depending on code rate.
