### ISSUE TITLE
 cmake .. -DCMAKE_BUILD_TYPE=Debug

### ISSUE THREAD

**Issue by deligeer** [drmpeg/gr-dvbs2rx#13]
after compile under  cmake .. -DCMAKE_BUILD_TYPE=Debug
while running  python3 dvbs2_rx_gdb.py
get following error
ImportError: /usr/local/lib/x86_64-linux-gnu/libgnuradio-dvbs2rx.so.1.0.0git: undefined symbol: _ZN29QuadratureAmplitudeModulationILi256ESt7complexIfEaE3AMPE

**Comment by deligeer** [comment]
cmake .. -DCMAKE_BUILD_TYPE=DEBUG
        make VERBOSE=1
        [ 18%] Linking CXX shared library libgnuradio-dvbs2rx.so
cd /home/goessdr/usrp_b210/gr-dvbs2rx/build/lib && /usr/bin/cmake -E cmake_link_script CMakeFiles/gnuradio-dvbs2rx.dir/link.txt --verbose=1
        /usr/bin/c++ -fPIC  -march=native -Wall -g  -shared -Wl,-soname,libgnuradio-dvbs2rx.so.1.0.0git -o libgnuradio-dvbs2rx.so.d88dc164 CMakeFiles/gnuradio-dvbs2rx.\
dir/bbdeheader_bb_impl.cc.o CMakeFiles/gnuradio-dvbs2rx.dir/bbdescrambler_bb_impl.cc.o CMakeFiles/gnuradio-dvbs2rx.dir/bch_decoder_bb_impl.cc.o CMakeFiles/gnuradio-dvb\
s2rx.dir/ldpc_decoder_cb_impl.cc.o  /usr/lib/x86_64-linux-gnu/libgnuradio-runtime.so.3.9.0.0-git /usr/lib/x86_64-linux-gnu/libgnuradio-pmt.so.3.9.0.0-git /usr/lib/x86_\
64-linux-gnu/libvolk.so.2.2 -ldl /usr/lib/x86_64-linux-gnu/liborc-0.4.so -lm /usr/lib/x86_64-linux-gnu/libboost_program_options.so.1.71.0 /usr/lib/x86_64-linux-gnu/lib\
boost_filesystem.so.1.71.0 /usr/lib/x86_64-linux-gnu/libboost_system.so.1.71.0 /usr/lib/x86_64-linux-gnu/libboost_regex.so.1.71.0 /usr/lib/x86_64-linux-gnu/libboost_th\
read.so.1.71.0 /usr/lib/x86_64-linux-gnu/libboost_atomic.so.1.71.0 -lpthread /usr/lib/x86_64-linux-gnu/liblog4cpp.so /usr/lib/x86_64-linux-gnu/libgmpxx.so /usr/lib/x86\
_64-linux-gnu/libgmp.so /usr/lib/x86_64-linux-gnu/libpython3.8.so -lrt
        cd /home/goessdr/usrp_b210/gr-dvbs2rx/build/lib && /usr/bin/cmake -E cmake_symlink_library libgnuradio-dvbs2rx.so.d88dc164 libgnuradio-dvbs2rx.so.1.0.0git libg\
nuradio-dvbs2rx.so

**Comment by drmpeg** [comment]
I was able to reproduce this. It's a function of using -DCMAKE_BUILD_TYPE=DEBUG. For some unknown reason, the file qam.hh doesn't compile properly with -O0 optimization.

You can work around this problem by setting the optimization level to -O1. In lib/CMakeLists.txt, change the line:
```
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -march=native -Wall")
```
to:
```
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -march=native -Wall -O1")
```

**Comment by deligeer** [comment]
Dear drmpeg,
Thank you very much. the problem is solved. really appreciate.
