### ISSUE TITLE
Code refuses to link on Fedora 36

### ISSUE THREAD

**Issue by deeptho** [drmpeg/gr-dvbs2rx#18]
With the default compile flags, a linker error occurs on fedora 36 (linux, x86-64) because  that code is compiled without -fPIC, which is necessary for shared libraries:
`
ldpc_decoder/libldpc_decoder_avx2.a(ldpc_decoder_avx2.cc.o): relocation R_X86_64_32 against hidden symbol '_ZN9ldpc_avx211LdpcDecoderE' can not be used when making a shared object
`

I succeeded in making it link and run by adding, in
 lib/CMakeLists.txt: 
`+add_compile_options ( -fPIC )`

A second such change has to be made in 
in cpu_features/CMakeLists.txt  but that is a git submodule.
So my workaround is probably not the best solution.

**Comment by drmpeg** [comment]
I believe you've posted in the wrong repository. Shouldn't this be in https://github.com/igorauad/gr-dvbs2rx instead?

**Comment by deeptho** [comment]
Yes, you are right. Sorry for that.
