### ISSUE TITLE
error: ‘_mm256_max_epi64’ was not declared in this scope

### ISSUE THREAD

**Issue by khawatkom** [drmpeg/gr-dvbs2rx#2]
avx2.hh:952:36: error: ‘_mm256_min_epi64’ was not declared in this scope

**Comment by xdsopl** [comment]
You can remove or comment out the function wrapping that _mm256_min_epi64 intrinsic.
Do you see more compiler errors like that after removing and recompiling?
Ahmet

**Comment by khawatkom** [comment]
Thanks for the swift reply.
It works well
![ack](https://user-images.githubusercontent.com/17951090/52241057-0a728a80-28d3-11e9-8991-2e5902c2182f.png)

**Comment by drmpeg** [comment]
Looks like the issue is that _mm256_min_epi64 (and _mm256_max_epi64) are AVX-512 instructions.

**Comment by khawatkom** [comment]
yes, though I had the latest gcc on ubuntu 14.04
I also had an issue with (`static const int SIZE = x`) statement as being not valid inside union. As a workaround, I removed the declaration and replaced its value as hardcoded inside :

`  value_type v[SIZE]; `
 `uint_type u[SIZE];`

**Comment by xdsopl** [comment]
Thank you for reporting this!
Which compiler version did you use?
Ahmet

**Comment by khawatkom** [comment]
gcc 4.9
