### ISSUE TITLE
VL.SNR option shows all errors

### ISSUE THREAD

**Issue by khawatkom** [drmpeg/gr-dvbs2rx#4]
gr::log :WARN: dvb_bbheader_bb0 - Transport Stream sync error!
frame = 0, BCH decoder too many bit errors.
Baseband header crc failed.

**Comment by drmpeg** [comment]
Sorry, there's no VL-SNR support (for more than one reason)

1) No support for pi/4 BPSK in the LDPC decoder block.

2) No support for puncturing and shortening in the LDPC decoder block.

3) Recent optimization changes in the DVB-S2 transmitter blocks have broken VL-SNR. Even before that, it had never been tested and it's not known if it's correct. When a commercial VL-SNR receiver becomes available for testing, I'll revisit and validate VL-SNR on the transmitter side.
