### ISSUE TITLE
'Module' object has no attribute 'ldpc_decoder_cb'

### ISSUE THREAD

**Issue by bryansd4** [drmpeg/gr-dvbs2rx#5]
Hello, i am trying to use the package dvbs2rx, but when i execute the file on GNU Radio, it shows the following error: "'Module' object has no attribute 'ldpc_decoder_cb'". May you help me to solve this issue please?

**Comment by drmpeg** [comment]
How did you install GNU Radio? You have to install gr-dvbs2rx into the same directory that you installed GNU Radio.

If you used apt-get to install, then GNU Radio is in /usr. To install gr-dvbs2rx into /usr, you have to set an install prefix with cmake. Like so:

cmake -DCMAKE_INSTALL_PREFIX=/usr

**Comment by bryansd4** [comment]
Thank you! It worked!
