### ISSUE TITLE
ImportError: no module named dvbs2rx

### ISSUE THREAD

**Issue by reikiryma** [drmpeg/gr-dvbs2rx#9]
Hello, i encounter this problem when running the program. Can anyone help me with this?

**Comment by drmpeg** [comment]
How did you install GNU Radio? You have to install gr-dvbs2rx into the same directory that you installed GNU Radio.

If you used apt-get to install, then GNU Radio is in /usr. To install gr-dvbs2rx into /usr, you have to set an install prefix with cmake. Like so:

cmake -DCMAKE_INSTALL_PREFIX=/usr
